# Ref
# https://circleci.com/blog/using-circleci-workflows-to-replicate-docker-hub-automated-builds/
 version: 2.1
 executors:
  docker-publisher:
    environment:
      IMAGE_HC: mkopa.azurecr.io/webhealthstats
      IMAGE_CUSTOMERS: mkopa.azurecr.io/customers
      IMAGE_ACCOUNTS: mkopa.azurecr.io/accounts
    docker:
      - image: circleci/buildpack-deps:stretch
 jobs:
# CUSTOMERS api
   build:
     executor: docker-publisher
     steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -f src/Services/Customers/API/Customers.API/Dockerfile -t IMAGE_CUSTOMERS:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
   publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Login to Azure acr
          command: docker login --username $AZURE_USERNAME --password $AZURE_ACR_PASS mkopa.azurecr.io
      - run:
          name: Publish Docker Image to Azure acr Hub
          command: |
            IMAGE_TAG="0.0.${CIRCLE_BUILD_NUM}"
            docker tag $IMAGE_CUSTOMERS:latest $IMAGE_CUSTOMERS:$IMAGE_TAG
            docker push $IMAGE_CUSTOMERS:latest
            docker push $IMAGE_CUSTOMERS:$IMAGE_TAG
   publish-tag:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Login to Azure acr
          command: docker login --username $AZURE_USERNAME --password $AZURE_ACR_PASS mkopa.azurecr.io
      - run:
          name: Publish Docker Tag to ACR
          command: |
            IMAGE_TAG=${CIRCLE_TAG/v/''}
            docker tag $IMAGE_CUSTOMERS:latest $IMAGE_CUSTOMERS:$IMAGE_TAG
            docker push $IMAGE_CUSTOMERS:latest
            docker push $IMAGE_CUSTOMERS:$IMAGE_TAG

# ACCOUNTS API
# LEDGER API
# LOANING API

# Work flows
 workflows:
  version: 2
  build-master:
    jobs:
        