version: '3.4'

services:
  accounts.api:
    image: ${DOCKER_REGISTRY-}accountsapi
    build:
      context: .
      dockerfile: src/Services/Accounts/API/Accounts.API/Dockerfile

  customers.api:
    image: ${DOCKER_REGISTRY-}customersapi
    build:
      context: .
      dockerfile: src/Services/Customers/API/Customers.API/Dockerfile

