apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountsapideployment
  namespace: mkopanamespace
spec:
  selector:
    matchLabels:
      app: accountsapi
  template:
    metadata:
      labels:
        app: accountsapi
    spec:
      containers:
      - name: accountsapi
        image: brainykatsys.azurecr.io/accountsapi
        imagePullPolicy: Always
        resources:
          limits:
            memory: 250Mi
            cpu: 250m
        ports:
        - containerPort: 80
        #envFrom:
        #    - configMapRef:
        #        name: clients-api-config